name: Lint JS and CSS

on:
    push:
        branches: [main, stage, develop]
    pull_request:
        branches: [main, stage, develop]
        paths:
            - '**.css'
            - '**.js'
            - '**.json'
            - '**.yml'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: 'package.json'
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Run linters
              run: npm run lint
